# Generated by Django 6.0.1 on 2026-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_ciudadmodel_alter_role_is_active_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadmodel',
            name='slug',
            field=models.SlugField(help_text='(Obligatorio)', unique=True, verbose_name='Slug'),
        ),
    ]
