# Generated by Django 6.0.1 on 2026-02-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(default=1, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='animal',
            name='localizacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animales',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
