# Generated by Django 6.0.1 on 2026-02-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0003_alter_animal_categoria_alter_animal_localizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='duenyo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='es_refugio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animals'),
        ),
    ]
