# Generated by Django 6.0.1 on 2026-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0004_animal_duenyo_animal_es_refugio_animal_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('localizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('categoria', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Otro', max_length=50)),
            ],
            options={
                'verbose_name': 'Encontrado',
                'verbose_name_plural': 'Encontrados',
                'db_table': 'encontrados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duenyo', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.IntegerField(default=1, verbose_name='Edad')),
                ('localizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('es_refugio', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Otro', max_length=50)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duenyo', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.IntegerField(default=1, verbose_name='Edad')),
                ('localizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('es_refugio', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Otro', max_length=50)),
            ],
            options={
                'verbose_name': 'Perdido',
                'verbose_name_plural': 'Perdidos',
                'db_table': 'perdidos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nombre'], 'verbose_name': 'Adoptados', 'verbose_name_plural': 'Adoptados'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animals/'),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='adoptados',
        ),
    ]
