# Generated by Django 6.0.1 on 2026-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0005_encontrados_favoritos_perdidos_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raza',
            field=models.CharField(default='sin raza', max_length=200),
        ),
        migrations.AddField(
            model_name='encontrados',
            name='raza',
            field=models.CharField(default='sin raza', max_length=200),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='raza',
            field=models.CharField(default='sin raza', max_length=200),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='raza',
            field=models.CharField(default='sin raza', max_length=200),
        ),
    ]
