# Generated by Django 6.0.1 on 2026-02-27 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0006_animal_raza_encontrados_raza_favoritos_raza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duenyo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('localizacion', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='Otro', max_length=50)),
                ('es_refugio', models.BooleanField(default=False)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animals/')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='duenyo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño'),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='duenyo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dueño'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritos',
            unique_together={('nombre', 'duenyo', 'localizacion')},
        ),
        migrations.CreateModel(
            name='MascotaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
